package hashtable.FindTheDifference_389;

/**
 * 389. Find the Difference
 * https://leetcode.com/problems/find-the-difference/
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a
 * random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class Solution {
    // tc O(n), sc O(1)
    // hashtable
    public char findTheDifference(String s, String t) {
        int[] smap = new int[26];
        for (char c : s.toCharArray()) {
            smap[c - 'a']++;
        }
        for (char c : t.toCharArray()) {
            smap[c - 'a']--;
        }
        for (int i = 0; i < smap.length; i++) {
            if (smap[i] < 0) return (char) ('a' + i);
        }
        return 'a';
    }

    // tc O(n), sc O(1)
    // bit manipulation
    public char findTheDifference1(String s, String t) {
        char num = 0;
        for (int i = 0; i < s.length(); i++) {
            num ^= (s.charAt(i) ^ t.charAt(i));
        }
        num ^= t.charAt(t.length() - 1);
        return num;
    }
}
